import os

# Database
DB_URL = os.environ['DB_URL']


# Auth
JWT_SECRET = os.environ['JWT_SECRET']
JWT_ALGORITHM = os.environ.get('JWT_ALGORITHM', 'HS256')

PASSWORD_SALT_LENGTH = int(os.environ['PASSWORD_SALT_LENGTH'])
PASSWORD_HASH_ALGORITHM = os.environ.get('PASSWORD_HASH_ALGORITHM', 'SHA256')
PASSWORD_HASH_ITERATIONS = int(os.environ.get('PASSWORD_HASH_ITERATIONS', 100000))
